version: '3.7'

services:
  # User service
  bit-scount-user-service:
    image: bit-scount-user-service:1.0
    hostname: bit-scount-user-service
    container_name: bit-scount-user-service
    networks:
      - logmonnet
    ports:
      - "8081:8081"

  # Notification
  bit-scount-backend-notification:
    image: bit-scount-backend-notification:1.0
    hostname: bit-scount-backend-notification
    container_name: bit-scount-backend-notification
    networks:
      - logmonnet
    ports:
      - "8082:8082"

  # Watchlist
  bit-scount-backend-watchlist:
    image: bit-scount-backend-watchlist:1.0
    hostname: bit-scount-backend-watchlist
    container_name: bit-scount-backend-watchlist
    networks:
      - logmonnet
    ports:
      - "8083:8083"

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - logmonnet
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    hostname: kibana
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - logmonnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Logstash instance 1
  logstash1:
    build: ../logstash
    hostname: logstash1
    container_name: logstash1
    networks:
      - logmonnet
    command: logstash -f /logstash-bit-scount-backend-notification.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  # Logstash instance 2
  logstash2:
    build: ../logstash
    hostname: logstash2
    container_name: logstash2
    networks:
      - logmonnet
    command: logstash -f /logstash-bit-scount-backend-watchlist.conf
    ports:
      - "5045:5045"
    depends_on:
      - elasticsearch

  # Logstash instance 3
  logstash3:
    build: ../logstash
    hostname: logstash3
    container_name: logstash3
    networks:
      - logmonnet
    command: logstash -f /logstash-bit-scount-user-service.conf
    ports:
      - "5046:5046"
    depends_on:
      - elasticsearch

networks:
  logmonnet:
    driver: bridge
