version: '3.7'

services:
    # User service
  bit-scount-user-service:
    image: bit-scount-user-service:1.0
    hostname: bit-scount-user-service
    container_name: bit-scount-user-service
    networks:
      - logmonnet
    ports:
      - "8081:8081"

  #notification
  bit-scount-backend-notification:
    image: bit-scount-backend-notification:1.0
    hostname: bit-scount-backend-notification
    container_name: bit-scount-backend-notification
    networks:
      - logmonnet
    ports:
      - "8082:8082"

  #watchlist
  bit-scount-backend-watchlist:
    image: bit-scount-backend-watchlist:1.0
    hostname: bit-scount-backend-watchlist
    container_name: bit-scount-backend-watchlist
    networks:
      - logmonnet
    ports:
      - "8083:8083"


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - logmonnet
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    hostname: kibana
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - logmonnet
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  
  logstash:
    build: ../logstash
    hostname: logstash
    container_name: logstash
    networks:
      - logmonnet
    command: logstash -f /conf/logstash-maid-account-manager.conf
    ports:
      - "5044:5044"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

networks:
  logmonnet:
    driver: "bridge"