FROM docker.elastic.co/logstash/logstash:7.6.0

ADD conf/logstash-bit-scount-backend-notification.conf /conf/logstash-bit-scount-backend-notification.conf
ADD conf/logstash-bit-scount-backend-watchlist.conf /conf/logstash-bit-scount-backend-watchlist.conf
ADD conf/logstash-bit-scount-user-service.conf /conf/logstash-bit-scount-user-service.conf
